# Generated by Django 5.0 on 2024-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
