# Generated by Django 5.0 on 2024-07-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_new_views_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory', verbose_name='Категория'),
        ),
    ]
