# Generated by Django 5.0 on 2024-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
